# Generated by Django 3.1.2 on 2020-10-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hall_name', models.CharField(max_length=50)),
                ('Hall_capacity', models.IntegerField()),
                ('Hall_area', models.TextField()),
                ('Hall_price', models.IntegerField()),
                ('Hall_catering', models.BooleanField()),
            ],
        ),
    ]
