# Generated by Django 3.1.2 on 2020-10-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='Hall_image',
            field=models.ImageField(default='', upload_to='home/image'),
        ),
    ]
